In [39]:
import numpy as np
from IPython.display import display, Markdown

In [40]:
# Функция для красивого вывода
def md(text):
    display(Markdown(text))

In [41]:
md("## Вариант 2 — Работа с матрицей NumPy (размерность 5×7)")

## Вариант 2 — Работа с матрицей NumPy (размерность 5×7)

In [43]:
# 1️⃣ Создаем матрицу 5x7 с индивидуальными значениями
matrix = np.array([
    [1, 3, 5, 7, 9, 11, 13],
    [2, 4, 6, 8, 10, 12, 14],
    [5, 10, 15, 20, 25, 30, 35],
    [3, 6, 9, 12, 15, 18, 21],
    [8, 16, 24, 32, 40, 48, 56]
])

array([[ 1,  3,  5,  7,  9, 11, 13],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 8, 16, 24, 32, 40, 48, 56]])

In [50]:
md("**1. Исходная матрица (5×7):**")
matrix

**1. Исходная матрица (5×7):**

array([[ 1,  3,  5,  7,  9, 11, 13],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 8, 16, 24, 32, 40, 48, 56]])

In [51]:
# 2️⃣ Определяем размерность матрицы
shape = matrix.shape
md(f"**2. Размерность матрицы:** {shape[0]} строк × {shape[1]} столбцов")

**2. Размерность матрицы:** 5 строк × 7 столбцов

In [52]:
# 3️⃣ Выделяем размерность объектов (строки и столбцы)
rows, cols = matrix.shape
md(f"**3. Количество строк:** {rows}, **Количество столбцов:** {cols}")

**3. Количество строк:** 5, **Количество столбцов:** 7

In [53]:
# 4️⃣ Индексация по колонкам (например, возьмём 2-й и 5-й столбцы)
indexed_columns = matrix[:, [1, 4]]
md("**4. Индексация по колонкам (2-й и 5-й):**")
indexed_columns

**4. Индексация по колонкам (2-й и 5-й):**

array([[ 3,  9],
       [ 4, 10],
       [10, 25],
       [ 6, 15],
       [16, 40]])

In [54]:
# 5️⃣ Поэлементная операция (вариант 2 — вычитание, например вычтем 2)
subtracted = matrix - 2
md("**5. Поэлементное вычитание 2 из каждого элемента:**")
subtracted

**5. Поэлементное вычитание 2 из каждого элемента:**

array([[-1,  1,  3,  5,  7,  9, 11],
       [ 0,  2,  4,  6,  8, 10, 12],
       [ 3,  8, 13, 18, 23, 28, 33],
       [ 1,  4,  7, 10, 13, 16, 19],
       [ 6, 14, 22, 30, 38, 46, 54]])

In [55]:
# 6️⃣ Применяем метод transpose (транспонирование)
transposed = matrix.transpose()
md("**6. Транспонированная матрица:**")
transposed

**6. Транспонированная матрица:**

array([[ 1,  2,  5,  3,  8],
       [ 3,  4, 10,  6, 16],
       [ 5,  6, 15,  9, 24],
       [ 7,  8, 20, 12, 32],
       [ 9, 10, 25, 15, 40],
       [11, 12, 30, 18, 48],
       [13, 14, 35, 21, 56]])