In [11]:
import numpy as np
from IPython.display import display, Markdown

In [12]:
# Вывод с форматированием
def md(text):
    display(Markdown(text))

In [13]:
md("## Вариант 2 — Работа с вектором NumPy `[4, 6, 3, 23, 56, 1, 9, 8]`")

## Вариант 2 — Работа с вектором NumPy `[4, 6, 3, 23, 56, 1, 9, 8]`

In [14]:
# 1 создание вектора
vector = np.array([4, 6, 3, 23, 56, 1, 9, 8])
md("**1. Исходный вектор:**")
display(vector)

**1. Исходный вектор:**

array([ 4,  6,  3, 23, 56,  1,  9,  8])

In [15]:
# 2 Индексация по элементам (3-й, 5-й, 7-й)
indexed_elements = vector[[2, 4, 6]]
md("**2. Индексация по элементам (индексы [2, 4, 6]):**")
display(indexed_elements)

**2. Индексация по элементам (индексы [2, 4, 6]):**

array([ 3, 56,  9])

In [16]:
# 3 Индексация по диапазону (с 2 по 5 включительно)
range_elements = vector[2:6]
md("**3. Индексация по диапазону (элементы 2–5):**")
display(range_elements)

**3. Индексация по диапазону (элементы 2–5):**

array([ 3, 23, 56,  1])

In [17]:
# 4 Переворачиваем массив
reversed_vector = vector[::-1]
md("**4. Перевернутый вектор:**")
display(reversed_vector)

**4. Перевернутый вектор:**

array([ 8,  9,  1, 56, 23,  3,  6,  4])

In [18]:
# 5 Операция присвоения (меняем элемент с индексом 3 на 100)
vector[3] = 100
md("**5. После присвоения (элемент 3 = 100):**")
display(vector)

**5. После присвоения (элемент 3 = 100):**

array([  4,   6,   3, 100,  56,   1,   9,   8])

In [19]:
# 6 Математическая операция (вариант 2 — деление)
divided = vector / 2
md("**6. Деление каждого элемента на 2:**")
display(divided)

**6. Деление каждого элемента на 2:**

array([ 2. ,  3. ,  1.5, 50. , 28. ,  0.5,  4.5,  4. ])

In [20]:
# 7 Argmax и Argmin
argmax_idx = vector.argmax()
argmin_idx = vector.argmin()
md(f"**7. Argmax:** индекс {argmax_idx}, значение {vector[argmax_idx]}")
md(f"**7. Argmin:** индекс {argmin_idx}, значение {vector[argmin_idx]}")

**7. Argmax:** индекс 3, значение 100

**7. Argmin:** индекс 5, значение 1

In [21]:
# 8 Метод append — добавляем 77
new_vector = np.append(vector, 77)
md("**8. После добавления элемента 77:**")
display(new_vector)

**8. После добавления элемента 77:**

array([  4,   6,   3, 100,  56,   1,   9,   8,  77])